// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProfile(arg1, arg2) {
  return window['go']['main']['App']['CreateProfile'](arg1, arg2);
}

export function DeleteItems(arg1) {
  return window['go']['main']['App']['DeleteItems'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DetectProfile(arg1) {
  return window['go']['main']['App']['DetectProfile'](arg1);
}

export function ForceReindex() {
  return window['go']['main']['App']['ForceReindex']();
}

export function GetActiveProfile() {
  return window['go']['main']['App']['GetActiveProfile']();
}

export function GetCatalog() {
  return window['go']['main']['App']['GetCatalog']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetPreviews(arg1) {
  return window['go']['main']['App']['GetPreviews'](arg1);
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function IndexerStatus() {
  return window['go']['main']['App']['IndexerStatus']();
}

export function ListMoveDestinations() {
  return window['go']['main']['App']['ListMoveDestinations']();
}

export function MoveItems(arg1, arg2) {
  return window['go']['main']['App']['MoveItems'](arg1, arg2);
}

export function OnCatalogUpdated() {
  return window['go']['main']['App']['OnCatalogUpdated']();
}

export function OnStatus(arg1) {
  return window['go']['main']['App']['OnStatus'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function RescanAll() {
  return window['go']['main']['App']['RescanAll']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectProfile(arg1) {
  return window['go']['main']['App']['SelectProfile'](arg1);
}

export function ThumbsDir() {
  return window['go']['main']['App']['ThumbsDir']();
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function UpdateItemMeta(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateItemMeta'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function UpdateProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2, arg3);
}
