// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';
import {indexer} from '../models';

export function DeleteItems(arg1:Array<number>):Promise<void>;

export function ForceReindex():Promise<void>;

export function GetCatalog():Promise<Array<main.TabDTO>>;

export function GetConfig():Promise<config.Config>;

export function GetPreviews(arg1:number):Promise<Array<string>>;

export function IndexerStatus():Promise<indexer.Status>;

export function ListMoveDestinations():Promise<Array<main.MoveDestDTO>>;

export function MoveItems(arg1:Array<number>,arg2:string):Promise<void>;

export function OnCatalogUpdated():Promise<void>;

export function OnStatus(arg1:indexer.Status):Promise<void>;

export function OpenFolder(arg1:number):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PickFolder():Promise<string>;

export function RescanAll():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function ToggleFavorite(arg1:number):Promise<boolean>;

export function UpdateItemMeta(arg1:number,arg2:string,arg3:Array<string>,arg4:string,arg5:string,arg6:boolean,arg7:boolean):Promise<void>;
